### ISSUE TITLE
Handle shutdown gracefully

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/k8s_01#73]
Theres a chance that shutting down when theres an event midflight can cause issues

```
27.07.2023 07:18:27.299 [ERROR] [com.teragrep.k8s_01.RelpOutput] [pool-5-thread-1] [#3] Failed to send messages: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at com.teragrep.rlp_01.RelpClientPlainSocket.read(RelpClientPlainSocket.java:168)
        at com.teragrep.rlp_01.RelpConnection.readAcks(RelpConnection.java:250)
        at com.teragrep.rlp_01.RelpConnection.sendBatch(RelpConnection.java:236)
        at com.teragrep.rlp_01.RelpConnection.commit(RelpConnection.java:210)
        at com.teragrep.k8s_01.RelpOutput.send(RelpOutput.java:163)
        at com.teragrep.k8s_01.K8SConsumer.accept(K8SConsumer.java:312)
        at com.teragrep.k8s_01.K8SConsumer.accept(K8SConsumer.java:49)
        at com.teragrep.rlo_13.MonitoredFileConsumer.readFile(MonitoredFileConsumer.java:133)
        at com.teragrep.rlo_13.MonitoredFileConsumer.accept(MonitoredFileConsumer.java:177)
        at com.teragrep.rlo_13.MonitoredFileConsumer.accept(MonitoredFileConsumer.java:33)
        at com.teragrep.rlo_12.FileTask.run(FileTask.java:63)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

```
27.07.2023 07:21:34.218 [ERROR] [com.teragrep.k8s_01.RelpOutput] [pool-6-thread-1] [#4] Failed to send messages: java.io.IOException: read failed
        at com.teragrep.rlp_01.RelpClientPlainSocket.read(RelpClientPlainSocket.java:173)
        at com.teragrep.rlp_01.RelpConnection.readAcks(RelpConnection.java:250)
        at com.teragrep.rlp_01.RelpConnection.sendBatch(RelpConnection.java:236)
        at com.teragrep.rlp_01.RelpConnection.commit(RelpConnection.java:210)
        at com.teragrep.k8s_01.RelpOutput.send(RelpOutput.java:163)
        at com.teragrep.k8s_01.K8SConsumer.accept(K8SConsumer.java:312)
        at com.teragrep.k8s_01.K8SConsumer.accept(K8SConsumer.java:49)
        at com.teragrep.rlo_13.MonitoredFileConsumer.readFile(MonitoredFileConsumer.java:133)
        at com.teragrep.rlo_13.MonitoredFileConsumer.accept(MonitoredFileConsumer.java:177)
        at com.teragrep.rlo_13.MonitoredFileConsumer.accept(MonitoredFileConsumer.java:33)
        at com.teragrep.rlo_12.FileTask.run(FileTask.java:63)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by StrongestNumber9** [comment]
This might be an issue only when k8s_01 is not `exec`'d as signals do not get passed properly

**Comment by StrongestNumber9** [comment]
I see no issues when `exec`ing so closing this
